const langcode = {
  Tamil: "ta",
  English: "en",
  Arabic: "ar",
  Spanish: "es",
  Hindi: "hi",
  Portuguese: "pt",
  French: "fr",
  Afrikaans: "af",
  Bosnian: "bs",
  Chinese: "zh",
  Croatian: "hr",
  Czech: "cs",
  Danish: "da",
  Dutch: "nl",
  Estonian: "et",
  German: "de",
  Hungarian: "hu",
  Norwegian: "no",
  Polish: "pl",
  Russian: "ru",
  Swedish: "sv",
};
const lang_convert = {
  Tamil: "தமிழ்",
  English: "English",
  Arabic: "العربية",
  Spanish: "Español",
  Hindi: "हिंदी",
  Portuguese: "Português",
  French: "français",
  Afrikaans: "Afrikaans",
  Bosnian: "bosanski",
  Chinese: "中文",
  Croatian: "Hrvatski",
  Czech: "čeština",
  Danish: "dansk",
  Dutch: "Dutch",
  Estonian: "Eestlane",
  German: "Deutsche",
  Hungarian: "Magyar",
  Norwegian: "Norsk",
  Polish: "Polskie",
  Russian: "Pусский",
  Swedish: "Svenska",
};

module.exports = { langcode, lang_convert };
